name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[Bug]:')
    steps:
    - uses: github/issue-labeler@v3.4 #May not be the latest version
      with:
        configuration-path: .github/issue-labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ secrets.ZYK_PERSONAL_TOKEN }}
        include-title: 1