name: "Close stale resolved issues"
on:
  schedule:
    - cron: '*/3 * * * *' 

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.ZYK_PERSONAL_TOKEN }}

          # 只处理带有 resolved 标签的 issue
          only-labels: 'resolved'

          # 3 天后标记为 stale
          days-before-stale: 0.03
          stale-issue-label: 'stale'
          stale-issue-message: |
            这个 Issue 标记为 resolved 且有一段时间未进一步更新，
            因此我们将其标记为 "stale"（闲置）状态。
            若你认为这是误操作，可随时评论移除 "stale" 标签。
            标记为 stale 的 Issue 在 4 天内无更新活动将自动关闭。

          # 4 天后关闭 stale 的 issue
          days-before-close: 0.03
          close-issue-message: |
            由于长时间未回复，我们先关闭 issue。
            后续有新诉求，可重新打开或新提 issue。

          # 当 issue 有更新时，自动移除 stale 标签（默认 true）
          remove-stale-when-updated: true
          # 同时移除 resolved 标签
          labels-to-remove-when-unstale: 'resolved'

          # 避免误操作 PR（如果需要也可以处理 PR，这里只针对 issue）
          days-before-pr-stale: -1
          days-before-pr-close: -1