name: "Close stale resolved issues"
on:
  schedule:
    - cron: '*/3 * * * *' 

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.ZYK_PERSONAL_TOKEN }}

          # Only process issues with the 'resolved' label
          only-labels: 'resolved'

          # Mark as stale after a period of inactivity
          days-before-stale: 0.03
          stale-issue-label: 'stale'
          stale-issue-message: |
            This issue has been marked as "resolved" and has not seen any recent activity. 
            As a result, it is now being labeled as "stale". 
            If you believe this is in error, please update the issue to remove the "stale" label. 
            Stale issues will be automatically closed if no further activity occurs.

          # Close stale issues after a period of inactivity
          days-before-close: 0.03
          close-issue-message: |
            This issue is being closed due to a lack of recent activity. 
            If you have any further questions or requirements, please feel free to reopen this issue or create a new one.

          # Automatically remove the 'stale' label when the issue is updated (default is true)
          remove-stale-when-updated: true
          # Also remove the 'resolved' label
          labels-to-remove-when-unstale: 'resolved'

          # Avoid accidental PR processing (PRs can be handled if needed; this is issue-only)
          days-before-pr-stale: -1
          days-before-pr-close: -1